<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOWjetFi\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOWjetFi/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerOWjetFi.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerOWjetFi\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerOWjetFi\App_KernelTestDebugContainer([
    'container.build_hash' => 'OWjetFi',
    'container.build_id' => '4360a0cd',
    'container.build_time' => 1657979040,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOWjetFi');
