<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'a_propos' => [[], ['_controller' => 'App\\Controller\\AProposController::index'], [], [['text', '/a_propos']], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\Admin\\DashboardController::index'], [], [['text', '/admin']], [], []],
    'actualites' => [[], ['_controller' => 'App\\Controller\\BlogpostController::actualites'], [], [['text', '/actualites']], [], []],
    'actualites_detail' => [['slug'], ['_controller' => 'App\\Controller\\BlogpostController::detail'], [], [['variable', '/', '[^/]++', 'slug', true], ['text', '/actualites']], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\ContactController::index'], [], [['text', '/contact']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'realisations' => [[], ['_controller' => 'App\\Controller\\PeintureController::realisations'], [], [['text', '/realisations']], [], []],
    'realisations_details' => [['slug'], ['_controller' => 'App\\Controller\\PeintureController::details'], [], [['variable', '/', '[^/]++', 'slug', true], ['text', '/realisations']], [], []],
    'portfolio' => [[], ['_controller' => 'App\\Controller\\PortfolioController::index'], [], [['text', '/portfolio']], [], []],
    'portfolio_categorie' => [['slug'], ['_controller' => 'App\\Controller\\PortfolioController::categorie'], [], [['variable', '/', '[^/]++', 'slug', true], ['text', '/portfolio']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'liip_imagine_filter_runtime' => [['filter', 'hash', 'path'], ['_controller' => 'Liip\\ImagineBundle\\Controller\\ImagineController::filterRuntimeAction'], ['filter' => '[A-z0-9_-]*', 'path' => '.+'], [['variable', '/', '.+', 'path', true], ['variable', '/', '[^/]++', 'hash', true], ['text', '/rc'], ['variable', '/', '[A-z0-9_-]*', 'filter', true], ['text', '/media/cache/resolve']], [], []],
    'liip_imagine_filter' => [['filter', 'path'], ['_controller' => 'Liip\\ImagineBundle\\Controller\\ImagineController::filterAction'], ['filter' => '[A-z0-9_-]*', 'path' => '.+'], [['variable', '/', '.+', 'path', true], ['variable', '/', '[A-z0-9_-]*', 'filter', true], ['text', '/media/cache/resolve']], [], []],
];
