# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    data_loader: default
    cache: default
    filter_sets:
        carre:
            quality: 80
            filters:
                upscale:
                    min: [800, 400]
                thumbail:
                    size: [800, 400]
                    mode: outbound
        banniere:
            quality: 75
            filters:
                thumbail:
                    size: [300, 300]
                    mode: outbound
