<?php

namespace ContainerOWjetFi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPeintureService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.vMByqdR.App\Entity\Peinture' shared service.
     *
     * @return \App\Entity\Peinture
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.vMByqdR": it references class "App\\Entity\\Peinture" but no such service exists.');
    }
}
