<?php

namespace ContainerOWjetFi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendContactCommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Command\SendContactCommand' shared autowired service.
     *
     * @return \App\Command\SendContactCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'SendContactCommand.php';

        $container->privates['App\\Command\\SendContactCommand'] = $instance = new \App\Command\SendContactCommand(($container->privates['App\\Repository\\ContactRepository'] ?? $container->load('getContactRepositoryService')), ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')), ($container->privates['App\\Service\\ContactService'] ?? $container->load('getContactServiceService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')));

        $instance->setName('app:send-contact');

        return $instance;
    }
}
