<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1QdsZwj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1QdsZwj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1QdsZwj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1QdsZwj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1QdsZwj\App_KernelDevDebugContainer([
    'container.build_hash' => '1QdsZwj',
    'container.build_id' => '5a6d0a72',
    'container.build_time' => 1657984045,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1QdsZwj');
