<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.61b1725c.js',
                '/build/640.9fcb99bc.js',
                '/build/app.010bf49f.js',
            ],
            'css' => [
                '/build/app.506cd86f.css',
            ],
        ],
    ],
],

]];
