<?php

namespace ContainerRwyNRxh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPeintureRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\PeintureRepository' shared autowired service.
     *
     * @return \App\Repository\PeintureRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'PeintureRepository.php';

        return $container->privates['App\\Repository\\PeintureRepository'] = new \App\Repository\PeintureRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
